FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
run pip install --ignore-installed pyOpenSSL --upgrade
run apt-get update
run apt-get install memcached
run service memcached start
CMD python manage.py migrate \
  && python manage.py runserver 0:8000





