# Generated by Django 2.2.2 on 2019-07-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('coursys_access_token', models.CharField(max_length=256)),
                ('coursys_access_token_secret', models.CharField(max_length=256)),
                ('canvas_token', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursysRequestToken',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coursys', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('request_token', models.CharField(max_length=256)),
                ('request_token_secret', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=1024)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
