# Generated by Django 2.2.2 on 2019-08-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursysrequesttoken',
            name='authorize_url',
            field=models.CharField(default='https://coursys.sfu.ca/', max_length=256),
            preserve_default=False,
        ),
    ]
